CREATE TABLE credit_card (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 10, INCREMENT BY 1) PRIMARY KEY,
  nick_name VARCHAR(30),
  card_type VARCHAR(30),
  card_sub_type VARCHAR(30),
card_holder_name VARCHAR(30),
user_id VARCHAR(30),
card_number VARCHAR(30)--,
--created date,
--updated date
);